### ISSUE TITLE
broken link: tutorial on depositing and withdrawing doesn't work

### ISSUE THREAD

**Issue by thibauld** [ethereum-optimism/optimism-tutorial#106]
On this page: https://github.com/ethereum-optimism/optimism-tutorial/tree/main/standard-bridge-custom-token
At the very bottom:
![image](https://user-images.githubusercontent.com/197119/171699279-fe5f02b1-49cf-4fa4-a261-518a0584e1f5.png)
Link is broken :point_up:

**Comment by thibauld** [comment]
And it's broken in your doc as well:
![image](https://user-images.githubusercontent.com/197119/171699548-b91b5d40-4588-4114-9ec0-f7a42af4092b.png)
([here](https://community.optimism.io/docs/developers/bridge/standard-bridge/#withdrawing-erc20s))

**Comment by qbzzt** [comment]
Thank you, PR submitted #108

**Comment by qbzzt** [comment]
It's been merged, so I'm closing the issue.
