### ISSUE TITLE
Tutorial broken with current @eth-optimism/plugins

### ISSUE THREAD

**Issue by alexfmpe** [ethereum-optimism/optimism-tutorial#16]
**Describe the bug**
Tutorial broken with @eth-optimism/plugins version currently installed when following the instructions. Using an older version, e.g. `yarn add @eth-optimism/plugins@0.0.20` runs into #8 instead

**To Reproduce**
Steps to reproduce the behavior: follow the tutorial - the [testing again](https://github.com/ethereum-optimism/optimism-tutorial/tree/5838865fbec11d53239ae2f7b6e8a438c9c59459#testing-again) step fails with 
`Error: Cannot find module '@eth-optimism/plugins/hardhat/ethers'`

**Expected behavior**
All tutorial steps working

**Additional context**
https://github.com/ethereum-optimism/plugins/pull/31 seems to have caused it

**Comment by platocrat** [comment]
Hi @alexfmpe and thanks for opening this PR!

We actually currently have a PR (#9) that majorly updates the tutorial to match the new breaking changes in the latest stable release of `@eth-optimism/plugins` (version `1.0.0-alpha.1` and higher).

While I really appreciate you taking the time to make this PR for us, I'd suggest waiting for #9 to get reviewed and merged to see if you still experience any issues (you likely won't 😉).

Therefore, I'll be closing this PR for now.
