### ISSUE TITLE
Join

### ISSUE THREAD

**Issue by Bubak01** [ethereum-optimism/optimism-tutorial#187]
https://www.google.com/search?tbs=sbi:AMhZZivUEBq2najrDNrRobsIL7yOHM0uwurGe8osyyWgNOSKM-8Hg_1QHchHn0INjmnwziagv6UTHHMK74M9SOcfamL05z1f7uHQDkl_1JFjB8wPzTa7mGTRmL56v01EutJ8JRmJRXBo4mgJUHLEMukq-OI0-LPP_1Z9A&bshm=ncc/2

**Comment by Vladcrypto909** [comment]
thank u)

**Comment by sbvegan** [comment]
I don't recommend anyone click that link.
