### ISSUE TITLE
TARGET=ovm 'Target' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by rob-lw** [ethereum-optimism/optimism-tutorial#19]
**Describe the bug**
Followed instructions in Step:1 of the The Official™ Optimism Tutorial <https://github.com/ethereum-optimism/optimism-tutorial>. Compiled Solidity into EVM bytecode without any issues and then moved onto compiling an Optimistic Ethereum contract with the command `TARGET=ovm npx hardhat compile` which throws an ERROR: `'TARGET' is not recognized as an internal or external command,operable program or batch file.`

**To Reproduce**
1. Go to <https://github.com/ethereum-optimism/optimism-tutorial>
2. Follow tutorial instructions The Official™ Optimism Tutorial
3. Complete: Prerequisite Software
4. Complete: The Task
5. Complete: Step 1: Compiling your contracts (Compiling an Ethereum contract)
6.  Complete: Step 1: Compiling your contracts (Compiling an Optimistic Ethereum contract)
7. Run `TARGET=ovm npx hardhat compile` at the end of step 6 to complete 
8. Command in step 7 throws and error `'TARGET' is not recognized as an internal or external command,operable program or batch file.`

**Expected behavior**

**Screenshots**

**System Specs:**
 - OS: Windows 10
 - Package Version (or commit hash): 7994ba68ed6f9975b4a562811c91e790bee74cee

**Additional context**

**Comment by platocrat** [comment]
Thanks again for pointing this out

**Comment by garyng2000** [comment]
for windows, you need this package

https://www.npmjs.com/package/cross-env

and add your own script definition in package.json like this:

compile-ovm : "cross-env TARGET=ovm hardhat compile"

if you must do it interactively, the equivalent would be two seperate calls 'SET TARGET=ovm' then 'npx hardhat compile'

**Comment by smartcontracts** [comment]
We've gotten a lot of feedback about using `TARGET=ovm` and are going to be moving over to having per-network options. This was just merged into our plugins and a release was cut earlier this morning: https://github.com/ethereum-optimism/plugins/blob/7dedc0a8eb8a512f26721849fde8346be10565a8/src/hardhat/compiler/index.ts#L131

**Comment by smartcontracts** [comment]
So now the "correct" way to compile stuff for the ovm is to have an `optimism` network with the `ovm: true` field set. Then compilation would be:

```
npx hardhat --network optimism compile
```

The README for this tutorial was updated recently to reflect this. Sorry about the frequent changes! Just trying to respond to feedback as quickly as possible when it comes in.

**Comment by smartcontracts** [comment]
Going to close this since it *should* be solved in the latest version of this tutorial. Please feel free to reopen if you are still running into issues. Thank you again! <3
