### ISSUE TITLE
docker-compolse.yml has been moved to ops dir

### ISSUE THREAD

**Issue by rongyi** [ethereum-optimism/optimism-tutorial#24]
in readme
the step below

git clone git@github.com:ethereum-optimism/optimism.git
cd optimism
yarn
yarn build
docker-compose build # need to specify the compose file or just cd ops dir
docker-compose up

**Comment by platocrat** [comment]
Thanks for catching this!
[I've added a step to `cd ops` after `yarn build`.](https://github.com/ethereum-optimism/optimism-tutorial/commit/f14e620407c31e37bf4c85d7d173c85a8ba7cf3d)
