### ISSUE TITLE
The link to https://community.optimism.io/tutorial doesn't work

### ISSUE THREAD

**Issue by qbzzt** [ethereum-optimism/optimism-tutorial#33]
**Describe the bug**

That web page should direct to this tutorial.

**To Reproduce**

1. Go to [the homepage](https://optimism.io/) 
2.  Click **DEVELOPERS > Tutorial**
3. See the 404 error

**Expected behavior**

I'd expect the link to lead to this tutorial.

**Screenshots**

![tutorial_404](https://user-images.githubusercontent.com/12722969/118297704-2139bb80-b4a4-11eb-8235-aaa3afd5fe7e.png)

**Comment by platocrat** [comment]
Closing since this issue will be properly fixed in https://github.com/ethereum-optimism/frontends/issues/47
