### ISSUE TITLE
Can we skip the `docker-compose build`?

### ISSUE THREAD

**Issue by qbzzt** [ethereum-optimism/optimism-tutorial#35]
**Is your feature request related to a problem? Please describe.**

It takes a long time to do the `docker-compose build` step, as you acknowledge in the doc:

> Now we just need to download, build, and install our Optimistic Ethereum node by running the following commands. Please note that docker-compose build will take a while. We're working on improving this (sorry)!

**Describe the solution you'd like**

Put a docker image on a registry.

**Comment by smartcontracts** [comment]
I recommend that you create an issue on https://github.com/ethereum-optimism/optimism for better visibility! I definitely agree that we should have a published docker image that people can use, though.

**Comment by qbzzt** [comment]
Closed because https://github.com/ethereum-optimism/optimism/issues/888 is a better place for this.
