### ISSUE TITLE
Issue with package @eth-optimism/contracts when running docker-compose build

### ISSUE THREAD

**Issue by miroslavnedelchev** [ethereum-optimism/optimism-tutorial#36]
Hello, been following this tutorial [https://github.com/ethereum-optimism/optimism-tutorial](url) and everything runs smoothly until the part where I have to run **docker-compose build** command inside **ops** folder. I also tried install the packages with **yarn install --force** , but without any result.

My yarn version is 1.10.1.

Attaching screenshot of the error I'm stuck at:
[https://ibb.co/25qBxdz](https://ibb.co/25qBxdz)

As shown in the screenshot, the first errors appears at **@eth-optimism/contracts** package.

**Comment by smartcontracts** [comment]
What operating system are you using? If windows, this may be related to: https://github.com/ethereum-optimism/optimism/issues/558 which should've been fixed by https://github.com/ethereum-optimism/optimism/pull/953.

**Comment by miroslavnedelchev** [comment]
Hey, the already raised issues which you provided are not related to my issue, they're about compiling the smart contracts. I've done that already and my contracts are successfully compiling. I'm at the very end of the tutorial and the issue appears when running **docker-compose build** command inside **ops** folder.

Anyway I'm using Windows 10 and my nodejs version is 12.20.1.

I raised the same issue in the **Optimism** discord at **_contributing_** room and I saw other devs are complaining about the same errors, so it's not just me. Maybe something got broken recently in one of the packages? Attaching screenshot of other person which I don't know, but who is having the same issue as me ( He is also using Windows 10 ):

[https://ibb.co/RcCtKxK](url)

**Comment by smartcontracts** [comment]
Ok I'm taking a look at this now. Thanks for the report!

**Comment by smartcontracts** [comment]
A PR fixing this issue is open here: https://github.com/ethereum-optimism/optimism/pull/974. Please see the discussion over at hereum-optimism/optimism/issues/960 for more information and for instructions on how to try the PR out before it's merged.

**Comment by smartcontracts** [comment]
Should now be fixed by https://github.com/ethereum-optimism/optimism/pull/974. You can use the following instructions to get this working locally:

```
cd optimism
git checkout develop
git pull origin develop
git rm --cached -r .
git reset --hard
yarn clean
yarn build
cd ops
docker-compose down -v
docker-compose build
docker-compose up
```

**Comment by smartcontracts** [comment]
Going to close unless you're still seeing the issue after following those instructions. Thank you again for the report!

**Comment by miroslavnedelchev** [comment]
Everything is resolved now. Thanks a lot for the quick support!
