### ISSUE TITLE
Technical Quesion

### ISSUE THREAD

**Issue by cyrilnavessamuel** [ethereum-optimism/optimism-tutorial#38]
I am not sure if its the correct channel please excuse me.

Hello Team,

I am Cyril Naves, a doctoral student of university cote d 'azur and I am working on blockchain consensus for private networks.

I would like to ask you some questions as part of my thesis work, please.

I am interested in building a private network with optimism. My questions are:
1) Can optimism be used to create private networks locally? If yes can you please point me to a tutorial?

2) Can smart contract be deployed on optimism local private network? If yes can you please point me to the tutorial please?

3) What is consensus supported by optimism it is Proof of work or Proof of Authority like in Ethereum?

4) Also can you let me know the TPS measured in optimistic ethereum if you had tested?

Thanks for your help,
Cyril

**Comment by smartcontracts** [comment]
Copy/pasting the response I gave on Discord:

1) Can optimism be used to create private networks locally? If yes can you please point me to a tutorial?

I'm working on some docs for how to run an OP node (and also how to run an OP network). In the meantime, you can follow the docs in our README for information on how to spin up a local development network: https://github.com/ethereum-optimism/optimism#development-quick-start

2) Can smart contract be deployed on optimism local private network? If yes can you please point me to the tutorial please?

Once you have your own network running you can deploy anything you want. Follow this tutorial and just point it towards your own local node: https://github.com/ethereum-optimism/optimism-tutorial

3) What is consensus supported by optimism it is Proof of work or Proof of Authority like in Ethereum?

There is no consensus mechanism. Transactions ordering on the short term is determined by a single "Sequencer" node (currently operated by the Optimism team). You can also bypass the Sequencer and submit transactions directly on Ethereum.

4) Also can you let me know the TPS measured in optimistic ethereum if you had tested?

I have no clue on this one, let me ask.

**Comment by smartcontracts** [comment]
Closing as I think this is mostly answered but feel free to reopen if you have other questions. Generally speaking I would recommend asking questions like these as issues on the main monorepo: https://github.com/ethereum-optimism/optimism/issues. It will get more attention there.
