### ISSUE TITLE
Cannot read property 'L1CrossDomainMessenger' of undefined

### ISSUE THREAD

**Issue by gakonst** [ethereum-optimism/optimism-tutorial#4]
I am unable to run the x-chain tests, getting this error:

```
 1) Layer 1 <> Layer 2 ERC20 Transfers
       "before each" hook for "should do the full flow":
     TypeError: Cannot read property 'L1CrossDomainMessenger' of undefined
      at /Users/Georgios/paradigm/portfolio/optimism/optimism-tutorial/test/erc20-xdomain.spec.ts:118:112
      at step (test/erc20-xdomain.spec.ts:52:23)
      at Object.next (test/erc20-xdomain.spec.ts:33:53)
      at /Users/Georgios/paradigm/portfolio/optimism/optimism-tutorial/test/erc20-xdomain.spec.ts:27:71
      at new Promise (<anonymous>)
      at __awaiter (test/erc20-xdomain.spec.ts:23:12)
      at Context.<anonymous> (test/erc20-xdomain.spec.ts:115:37)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Steps to reproduce: 

```
git clone https://github.com/ethereum-optimism/optimism-tutorial/
cd optimism-tutorial
git checkout dev-xdomain
yarn
yarn compile
yarn test
```

This is an issue because `l2ethers.contracts` is undefined. Was it refactored somewhere?

**Comment by gakonst** [comment]
Turns out this happens because I ran `yarn add @eth-optimism/contracts` which installed a later version which seems to be incompatible with the current repo

**Comment by TransmissionsDev** [comment]
With the latest version of the plugins (`"@eth-optimism/plugins": "^0.0.16"`) I see a different error on the same set of lines:

<img width="817" alt="Screen Shot 2021-02-18 at 10 56 35 PM" src="https://user-images.githubusercontent.com/26209401/108469110-8df24080-723c-11eb-8faf-b631a8139064.png">

**Comment by kfichter** [comment]
Taking a look now.

**Comment by TransmissionsDev** [comment]
bump :p

**Comment by gakonst** [comment]
Closing given https://github.com/ethereum-optimism/optimism-tutorial/tree/deposit-withdrawal works. @kfichter could you please delete `dev-xdomain` since it's stale?
