### ISSUE TITLE
Switch out `@eth-optimism/watcher` for `@eth-optimism/core-utils`

### ISSUE THREAD

**Issue by transmissions11** [ethereum-optimism/optimism-tutorial#58]
https://github.com/ethereum-optimism/optimism-tutorial/blob/main/l1-l2-deposit-withdrawal/scripts/example.js#L2

The watcher hasn't been maintained for months, switching over to core utils would be a better example for devs.

**Comment by qbzzt** [comment]
@elenadimitrova , this is your code. Do you want to do it, or shall I?

**Comment by elenadimitrova** [comment]
@qbzzt please do, I won't get a chance in the next couple of days

**Comment by qbzzt** [comment]
Thank you for telling us about this issue. Consider it fixed.
