### ISSUE TITLE
L2 => L1 transaction on optimism local test network hangs when waiting to be relayed to L1

### ISSUE THREAD

**Issue by gwalen** [ethereum-optimism/optimism-tutorial#84]
L2 => L1 transaction on miannet must wait 7 days and on Kovan it's 60s, on optimism local network it also should a short time.
but is hangs when waiting to be relayed to L1. 

Steps to reproduce   :
1. start local optimism nodes with docker-compose (https://github.com/ethereum-optimism/optimism-tutorial/tree/main/hardhat) :
`docker-compose -f docker-compose-nobuild.yml up -t 3600`
2. run the l1-l2-deposit-withdrawal tutorial app (https://github.com/ethereum-optimism/optimism-tutorial/tree/main/l1-l2-deposit-withdrawal):
`node scripts/example.js`

output:
```
Deploying L1 ERC20...
   L1_ERC20 deployed @ 0x3Aa...c
Deploying L2 ERC20...
   L2_ERC20 deployed @ 0x5Fb...3
Instantiate L1 Standard Bridge...
Balance on L1: 1234
Balance on L2: 0
Approving tokens for Standard Bridge...
Depositing tokens into L2 ...
Waiting for deposit to be relayed to L2...
Balance on L1: 0
Balance on L2: 1234
Withdrawing tokens back to L1 ...
Waiting for withdrawal to be relayed to L1...
(...freeze...)
```

**Comment by markdawson** [comment]
I also experience this

**Comment by ADTClone** [comment]
I had the same issue with the nobuild image.

When I built it from scratch I didn't have the issue. I noticed building from scratch that the deployer.sh script was run which picks up the environment variables in the docker-compose and applies them. Wondering if the nobuild images are out of date - but doesn't seem the environment variables are being set with them.

**Comment by qbzzt** [comment]
Sorry. Right now we're working on an SDK that will make it a lot easier, and as part of that SDK we'll release tutorials.

**Comment by qbzzt** [comment]
Sorry for the delay, but the tutorial is almost ready and you can see it already in the PR.

**Comment by 0xMySt1c** [comment]
I ran into this issue as well, but running 
```
docker-compose up --scale relayer=1
```
fixed the issue for me

**Comment by zmeghji** [comment]
Thanks @0xMySt1c . That worked for me too.
