### ISSUE TITLE
Update tutorials to run the correct docker-compose file

### ISSUE THREAD

**Issue by tonykogias** [ethereum-optimism/optimism-tutorial#94]
In a recent commit `docker-compose-nobuild.yml` was removed so the instruction on running a local node don't work. 

change 
`docker-compose -f docker-compose-nobuild.yml up -t 3600`

to 
`docker-compose -f docker-compose.yml up -t 3600`

in tutorials README, at "Start an Optimistic Ethereum Node" paragraph.

**Comment by qbzzt** [comment]
I agree. However, these tutorials are being revamped (see #87), and they'll all refer to the dev-node page in the developer documentation, which is being updated now (see https://github.com/ethereum-optimism/community-hub/pull/368).

**Comment by tonykogias** [comment]
That's great! I have noticed that PR, I suppose if it gets merged soon we can close this.
