### ISSUE TITLE
Insufficient fund error on L2 geth for the hardhat example

### ISSUE THREAD

**Issue by jingzhaoou** [ethereum-optimism/optimism-tutorial#97]
I followed the instructions to create a local Optimism network. Basically, I checked out the Optimism monorepo and ran the the following under the `ops` folder:

```
docker-compose up -d
```

I connected to the L1 hardhat network and saw the default 20 accounts (each with 5000ETH). I created a smart contract on the L1 network by connecting to port 9454 directly. Things worked all fine with the L1 network. 

However, when I tried to create a smart contract on the L2geth network, I ran into the following error:

```
reason: 'insufficient funds for intrinsic transaction cost',
  code: 'INSUFFICIENT_FUNDS',
  error: ProviderError: invalid transaction: insufficient funds for gas * price + value
      at HttpProvider.request (/Users/jou2019/workspace/hello-world/node_modules/hardhat/src/internal/core/providers/http.ts:74:19)
      at GanacheGasMultiplierProvider.request (/Users/jou2019/workspace/hello-world/node_modules/hardhat/src/internal/core/providers/gas-providers.ts:312:34)
      at processTicksAndRejections (node:internal/process/task_queues:96:5),
  method: 'sendTransaction',
```

When I looked at the accounts and fund of the L2geth network, I saw a single account there (`0x00000398232e2064f896018496b4b44b3d62751f` in my case) with 0ETH. 

Not sure if that is a bug or not. The instructions seem to indicate the 20 L1 test accounts should be created for both L1 and L2 with funds. Or maybe that single account with 0 fund is expected. I cannot find instructions how to move forward to "create" fund myself on the L2 network. Wonder if anyone can give me some help on how to move forward. Thanks a lot in advance.

**Comment by qbzzt** [comment]
I'll look into it tonight.

**Comment by qbzzt** [comment]
We're in the process of updating these instructions. The latest (soon to be published) is at https://github.com/ethereum-optimism/community-hub/blob/8ac6460f6fcd47a205f2556481a2b57f7f22be0f/src/docs/developers/build/dev-node.md .

The L2 accounts should be the same addresses as the L1 accounts (the result of the mnemonic `test test test ... test junk`). Can you check the balance of those?

**Comment by jingzhaoou** [comment]
@qbzzt Thank you so much for the help. The to-be-published tutorial is great! Hope this is valuable to other newbies, I need to use `mnemonic`  in `hardhat.config.js` when connecting to the L2 network. 

```
  networks: {
    l2: {
      url: "http://localhost:8545",
      accounts: { mnemonic: 'test test test test test test test test test test test junk' }
    },
    l1: {
      url: "http://localhost:9545",
      accounts: { mnemonic: 'test test test test test test test test test test test junk' }
    },
```

After that, I use the following scripts to check the accounts and their balances:

```
task("accounts", "Prints the list of accounts", async (taskArgs, hre) => {
  const accounts = await hre.ethers.getSigners();

  for (const account of accounts) {
    const address = account.address;
    const balance = await web3.eth.getBalance(address);
    const num_eth = web3.utils.fromWei(balance, "ether");
    console.log(`${address}: ${num_eth} ETH`);
  }
});
```

And verified all my accounts at the L2 network have the same amount of funds as the L1 network.
